# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, verbose_name='Name of the Channel')),
                ('channel_description', models.CharField(blank=True, max_length=4096)),
            ],
            options={
                'db_table': 'channels',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=255, verbose_name='Name of the Collection')),
                ('collection_description', models.CharField(blank=True, max_length=4096)),
            ],
            options={
                'db_table': 'collections',
            },
        ),
        migrations.CreateModel(
            name='CoordinateFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_name', models.CharField(max_length=255, verbose_name='Name of the Coordinate reference frame')),
                ('coord_description', models.CharField(blank=True, max_length=4096)),
                ('xextent', models.IntegerField()),
                ('yextent', models.IntegerField()),
                ('zextent', models.IntegerField()),
                ('xvoxelsize', models.FloatField(default=1.0)),
                ('yvoxelsize', models.FloatField(default=1.0)),
                ('zvoxelsize', models.FloatField(default=1.0)),
            ],
            options={
                'db_table': 'coordinate_frames',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=255, verbose_name='Name of the Dataset')),
                ('dataset_description', models.CharField(blank=True, max_length=4096)),
                ('is_source', models.CharField(choices=[(0, 'NO'), (1, 'YES')], max_length=100)),
                ('datatype', models.CharField(choices=[(0, 'uint8'), (1, 'uint16'), (2, 'uint32')], max_length=100)),
                ('coord_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coord', to='bosscore.CoordinateFrame')),
            ],
            options={
                'db_table': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_name', models.CharField(max_length=255, verbose_name='Name of the Experiment')),
                ('experiment_description', models.CharField(blank=True, max_length=4096)),
                ('num_resolution_levels', models.IntegerField(default=0)),
                ('heirarchy_method', models.CharField(choices=[(0, 'near_iso'), (1, 'iso'), (2, 'slice')], max_length=100)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='bosscore.Collection')),
            ],
            options={
                'db_table': 'experiments',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=255, verbose_name='Name of the Layer ')),
                ('layer_description', models.CharField(blank=True, max_length=4096)),
            ],
            options={
                'db_table': 'layers',
            },
        ),
        migrations.CreateModel(
            name='TimeSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_name', models.CharField(max_length=255, verbose_name='Name of the Time Sample ')),
                ('ts_description', models.CharField(blank=True, max_length=4096)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesamples', to='bosscore.Channel')),
            ],
            options={
                'db_table': 'timesamples',
            },
        ),
        migrations.AddField(
            model_name='layer',
            name='timesample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='bosscore.TimeSample'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='bosscore.Experiment'),
        ),
        migrations.AddField(
            model_name='channel',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='bosscore.Dataset'),
        ),
    ]
