# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bosscore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='default_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_channel', to='bosscore.Channel'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='default_layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_layer', to='bosscore.Layer'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='default_time_sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_time_sample', to='bosscore.TimeSample'),
        ),
    ]
