# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bossmeta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Name of the Channel')),
                ('channel_description', models.CharField(blank=True, max_length=4096)),
            ],
            options={
                'db_table': 'channels',
            },
        ),
        migrations.CreateModel(
            name='Coordinate_Frame',
            fields=[
                ('coord_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Name of the Coordinate reference frame')),
                ('coord_description', models.CharField(blank=True, max_length=4096)),
                ('xextent', models.IntegerField()),
                ('yextent', models.IntegerField()),
                ('zextent', models.IntegerField()),
                ('xvoxelsize', models.FloatField(default=1.0)),
                ('yvoxelsize', models.FloatField(default=1.0)),
                ('zvoxelsize', models.FloatField(default=1.0)),
            ],
            options={
                'db_table': 'coordinate_frames',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('dataset_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Name of the Dataset')),
                ('dataset_description', models.CharField(blank=True, max_length=4096)),
                ('is_source', models.CharField(choices=[(0, 'NO'), (1, 'YES')], max_length=100)),
                ('datatype', models.CharField(choices=[(0, 'uint8'), (1, 'uint16'), (2, 'uint32')], max_length=100)),
                ('coord_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coord', to='bossmeta.Coordinate_Frame')),
            ],
            options={
                'db_table': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('layer_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Name of the Time Sample ')),
                ('layer_description', models.CharField(blank=True, max_length=4096)),
            ],
            options={
                'db_table': 'layers',
            },
        ),
        migrations.CreateModel(
            name='Time_Sample',
            fields=[
                ('ts_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Name of the Time Sample ')),
                ('ts_description', models.CharField(blank=True, max_length=4096)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesamples', to='bossmeta.Channel')),
            ],
            options={
                'db_table': 'timesamples',
            },
        ),
        migrations.AlterField(
            model_name='experiment',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='bossmeta.Collection'),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='bossmeta.Time_Sample'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='bossmeta.Experiment'),
        ),
        migrations.AddField(
            model_name='channel',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='bossmeta.Dataset'),
        ),
    ]
