# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bossmeta', '0002_auto_20160124_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordinate_Frame',
            new_name='CoordinateFrame',
        ),
        migrations.RenameModel(
            old_name='Time_Sample',
            new_name='TimeSample',
        ),
        migrations.RenameField(
            model_name='layer',
            old_name='time_sample',
            new_name='timesample',
        ),
    ]
