# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-12 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'Preparing'), (1, 'Uploading'), (2, 'Complete'), (3, 'Deleted')], default=0)),
                ('upload_queue', models.URLField(max_length=512, null=True)),
                ('ingest_queue', models.URLField(max_length=512, null=True)),
                ('config_data', models.TextField()),
                ('collection', models.CharField(max_length=128)),
                ('experiment', models.CharField(max_length=128)),
                ('channel', models.CharField(max_length=128)),
                ('resolution', models.IntegerField()),
                ('x_start', models.IntegerField()),
                ('y_start', models.IntegerField()),
                ('z_start', models.IntegerField()),
                ('t_start', models.IntegerField()),
                ('x_stop', models.IntegerField()),
                ('y_stop', models.IntegerField()),
                ('z_stop', models.IntegerField()),
                ('t_stop', models.IntegerField()),
                ('tile_size_x', models.IntegerField()),
                ('tile_size_y', models.IntegerField()),
                ('tile_size_z', models.IntegerField()),
                ('tile_size_t', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ingest_job',
            },
        ),
    ]
