# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-03 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bossingest', '0002_ingestjob_tile_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestjob',
            name='step_function_arn',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='ingestjob',
            name='status',
            field=models.IntegerField(choices=[(0, 'Preparing'), (1, 'Uploading'), (2, 'Complete'), (3, 'Deleted'), (4, 'Failed')], default=0),
        ),
    ]
