# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-15 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bossingest', '0003_auto_20170303_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestjob',
            name='ingest_type',
            field=models.IntegerField(choices=[(0, 'Tile'), (1, 'Volumetric')], default=0),
        ),
    ]
