# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-15 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bossingest', '0004_ingestjob_ingest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingestjob',
            name='ingest_type',
        ),
    ]
