# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-02-20 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bossingest', '0005_remove_ingestjob_ingest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestjob',
            name='ingest_type',
            field=models.IntegerField(choices=[(0, 'Tile'), (1, 'Volumetric')], default=0),
        ),
    ]
