# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-06-27 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bossingest', '0006_ingestjob_ingest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestjob',
            name='channel_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ingestjob',
            name='collection_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ingestjob',
            name='experiment_id',
            field=models.IntegerField(null=True),
        ),
    ]
