# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-02-10 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bossingest', '0008_auto_20200123_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestjob',
            name='wait_on_queues_ts',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ingestjob',
            name='status',
            field=models.IntegerField(choices=[(0, 'Preparing'), (1, 'Uploading'), (2, 'Complete'), (3, 'Deleted'), (4, 'Failed'), (5, 'Completing'), (6, 'Wait on queues')], default=0),
        ),
    ]
