# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-23 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bosscore', '0002_auto_20161204_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='deleted_status',
            field=models.CharField(choices=[('started', 'STARTED'), ('finished', 'FINISHED'), ('error', 'ERROR')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='to_be_deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='deleted_status',
            field=models.CharField(choices=[('started', 'STARTED'), ('finished', 'FINISHED'), ('error', 'ERROR')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='to_be_deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coordinateframe',
            name='deleted_status',
            field=models.CharField(choices=[('started', 'STARTED'), ('finished', 'FINISHED'), ('error', 'ERROR')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coordinateframe',
            name='to_be_deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='deleted_status',
            field=models.CharField(choices=[('started', 'STARTED'), ('finished', 'FINISHED'), ('error', 'ERROR')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='to_be_deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='coord_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exps', to='bosscore.CoordinateFrame'),
        ),
    ]
