# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-03 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosscore', '0003_auto_20170123_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinateframe',
            name='time_step',
        ),
        migrations.RemoveField(
            model_name='coordinateframe',
            name='time_step_unit',
        ),
        migrations.AddField(
            model_name='experiment',
            name='time_step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='time_step_unit',
            field=models.CharField(blank=True, choices=[('nanoseconds', 'NANOSECONDS'), ('microseconds', 'MICROSECONDS'), ('milliseconds', 'MILLISECONDS'), ('seconds', 'SECONDS')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='deleted_status',
            field=models.CharField(blank=True, choices=[('started', 'STARTED'), ('finished', 'FINISHED'), ('error', 'ERROR')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='to_be_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='deleted_status',
            field=models.CharField(blank=True, choices=[('started', 'STARTED'), ('finished', 'FINISHED'), ('error', 'ERROR')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='to_be_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coordinateframe',
            name='deleted_status',
            field=models.CharField(blank=True, choices=[('started', 'STARTED'), ('finished', 'FINISHED'), ('error', 'ERROR')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coordinateframe',
            name='to_be_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='deleted_status',
            field=models.CharField(blank=True, choices=[('started', 'STARTED'), ('finished', 'FINISHED'), ('error', 'ERROR')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='to_be_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
