# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-14 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosscore', '0004_auto_20170303_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='downsample_arn',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='downsample_status',
            field=models.CharField(choices=[('NOT_DOWNSAMPLED', 'Not Downsampled'), ('IN_PROGRESS', 'In Progress'), ('DOWNSAMPLED', 'Downsampled'), ('FAILED', 'Failed')], default='NOT_DOWNSAMPLED', max_length=100),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='hierarchy_method',
            field=models.CharField(choices=[('anisotropic', 'ANISOTROPIC'), ('isotropic', 'ISOTROPIC')], default='anisotropic', max_length=100),
        ),
    ]
