# Generated by Django 2.2.16 on 2020-10-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosscore', '0005_auto_20170414_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='downsample_status',
            field=models.CharField(choices=[('NOT_DOWNSAMPLED', 'Not Downsampled'), ('QUEUED', 'In Queue'), ('IN_PROGRESS', 'In Progress'), ('DOWNSAMPLED', 'Downsampled'), ('FAILED', 'Failed')], default='NOT_DOWNSAMPLED', max_length=100),
        ),
    ]
