# Generated by Django 2.2.16 on 2021-05-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosscore', '0007_throttlemetric_throttlethreshold_throttleusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='s3bucket',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='storage_type',
            field=models.CharField(choices=[('spdb', 'Boss Spatial Database'), ('cloudvol', 'CloudVolume')], default='spdb', max_length=30),
        ),
        migrations.AddField(
            model_name='collection',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
