# Generated by Django 2.2.16 on 2021-05-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosscore', '0008_auto_20210514_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='s3bucket',
            new_name='bucket',
        ),
        migrations.AddField(
            model_name='channel',
            name='cv_path',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
