# Generated by Django 2.2.18 on 2022-11-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosscore', '0009_auto_20210517_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'default_permissions': (), 'permissions': (('read', 'Can view resource'), ('update', 'Can update resource'), ('delete', 'Can delete resource'), ('add', 'Can add resources '), ('assign_group', 'Can assign groups permissions for the resource'), ('remove_group', 'Can remove groups permissions for the resource'), ('add_volumetric_data', 'Can add volumetric data for the channel'), ('read_volumetric_data', 'Can read volumetric data for the channel'), ('delete_volumetric_data', 'Can delete volumetric data for the channel'), ('add_metadata', 'Can add metadata for the channel'), ('read_metadata', 'Can read metadata for the channel'), ('update_metadata', 'Can read metadata for the channel'), ('delete_metadata', 'Can delete metadata for the channel'))},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'default_permissions': (), 'managed': True, 'permissions': (('read', 'Can view resource'), ('update', 'Can update resource'), ('delete', 'Can delete resource'), ('add', 'Can add resources '), ('assign_group', 'Can assign groups permissions for the resource'), ('remove_group', 'Can remove groups permissions for the resource'), ('add_metadata', 'Can add metadata for the channel'), ('read_metadata', 'Can read metadata for the channel'), ('update_metadata', 'Can read metadata for the channel'), ('delete_metadata', 'Can delete metadata for the channel'))},
        ),
        migrations.AlterModelOptions(
            name='experiment',
            options={'default_permissions': (), 'permissions': (('read', 'Can view resource'), ('update', 'Can update resource'), ('delete', 'Can delete resource'), ('add', 'Can add resources '), ('assign_group', 'Can assign groups permissions for the resource'), ('remove_group', 'Can remove groups permissions for the resource'), ('add_metadata', 'Can add metadata for the channel'), ('read_metadata', 'Can read metadata for the channel'), ('update_metadata', 'Can read metadata for the channel'), ('delete_metadata', 'Can delete metadata for the channel'))},
        ),
        migrations.AlterField(
            model_name='channel',
            name='cv_path',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='downsample_arn',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
