# Copyright 2016 The Johns Hopkins University Applied Physics Laboratory
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys
from pathlib import Path


"""
Base Django settings for boss project.

This file is imported by all other configurations of the boss.  Only put
items in here that are applicable to any configuration including local only
instances and production instances.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/

"""

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# This is overridden in production.py.
SECRET_KEY = 'cki+nch2)9b_xatlg1n-!(db07ctl#*qh8j-jr)0h!0+c0nbkr'

# SECURITY WARNING: don't run with debug turned on in production!
# This is overridden in production.py.
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'bosscore',
    'bossmeta',
    'bossspatialdb',
    'sso',
    'mgmt', # for templating to work
    'bootstrapform', # style management console
    'bossingest',
    'bossobject',
    #'rest_framework_swagger',
    'drf_yasg',
    'guardian'
]

#MIDDLEWARE_CLASSES = (
MIDDLEWARE = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # This one is now a pass-thru
    #'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
)

ROOT_URLCONF = 'boss.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'boss.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
# DBs are configured by the config files that import base.py.


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/static/'

ANONYMOUS_USER_NAME = None
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', # this is default
    'guardian.backends.ObjectPermissionBackend',
]


# Django rest framework versioning  and permission requirements
REST_FRAMEWORK = {
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DEFAULT_PERMISSION_CLASSES': (
        #'rest_framework.permissions.IsAuthenticated',
        #'rest_framework.permissions.DjangoModelPermissions'
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',

    )

}
# Version that unit tests are being run against
BOSS_VERSION = 'v1'

# Maximum number of bytes in an uncompressed matrix supported by the Cutout Service
CUTOUT_MAX_SIZE = 520 * 1048576

# Maximum number of pixels that non-privileged users can ingest (200 x 200 x 200 cubes)
INGEST_MAX_SIZE = (200 * 512) * (200 * 512) * (200 * 16)

# Maximum number of pixels that non-privileged users can downsample (200 x 200 x 200 cubes)
DOWNSAMPLE_MAX_SIZE = (200 * 512) * (200 * 512) * (200 * 16)

# Allow all cross site origins
CORS_ORIGIN_ALLOW_ALL = True

# Test RUN_HIGH_MEM_TESTS FLag
RUN_HIGH_MEM_TESTS = os.environ.get('RUN_HIGH_MEM_TESTS')

# Select nose2 test runner so testing Layers will work
TEST_RUNNER="djnose2.TestRunner"
